<a href="https://colab.research.google.com/github/yosephabate/2017-10-11-AAITTEST/blob/gh-pages/numpy_exercise_winc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from numpy.random import default_rng

In [2]:
rng = default_rng(1234)

In [3]:
mystery_array = (rng.integers(low=0, high=500, size=216)*
                 rng.integers(low=0, high=500, size=216))

In [5]:
mystery_array.size

216

In [6]:
mystery_array = mystery_array.reshape(6, 6, 6)

In [7]:
mystery_array.shape

(6, 6, 6)

In [8]:
mystery_array

array([[[116382, 151768, 171071,  29830,  35020,  63618],
        [  1352,  60320,  33810,  22101,   5628,  27966],
        [  9131,  12120, 111612,  44838, 147312,  91580],
        [ 43110,  52924,  44320,  13860,  24257, 144400],
        [204288, 156884,  96922,  37497, 121471, 116602],
        [228960,  15134,   1173, 102026, 128781,   5661]],

       [[106518,   1806, 121746,  85260, 117608,  10350],
        [ 19683, 123783,   7100, 111890,  27945,  89975],
        [ 17810,  13170,  37736, 130784,  76983,  10512],
        [106672,  18620,    768,    481,  69874,  49875],
        [ 34768,   1287,  80625, 100064,    870, 120009],
        [ 24081, 209755, 174924,   5776, 168019, 145824]],

       [[ 17444,  22841,  75650,  40420, 215254,   1333],
        [ 12292,  77688,  25585,   6210, 197976,  16660],
        [ 76760, 111538, 138240, 146888,  54120,  59220],
        [ 98792,  94304, 144774,  82695, 117312,  87001],
        [   724,  21298,   9906,   3277, 216480,   6700],
        [ 

In [9]:
mystery_array.shape

(6, 6, 6)

In [10]:
mystery_array.size

216

In [11]:
mystery_array.ndim

3

In [12]:
type(mystery_array)

numpy.ndarray

In [13]:
mystery_array[0, 0, 0] # mystery_array[0][0][0]

116382

In [15]:
mystery_array[5, 5, 5]

25668

In [19]:
mystery_array[2, 5, 2]

41976

In [26]:
mystery_array[4, 5, :]

array([  6624,  26892, 149100,  16720, 154912,  43290])

In [22]:
mystery_array[0, 2, 3:]

array([ 44838, 147312,  91580])

In [23]:
mystery_array[4, :, 4]

array([  6357,  22320,  11024,  21750,  71149, 154912])

In [24]:
mystery_array[4, :, 4].shape

(6,)